### ISSUE TITLE
RuntimeError in ModerateParameters::Parameters#require

### ISSUE THREAD

**Issue by bestwebua** [hintmedia/moderate_parameters#22]
Hello! First of all thanks for nice tool. It can help to improve old apps. Today I have faced with RuntimeError in `ModerateParameters::Parameters#require` on latest (0.4.0) version. Any idea how to debug and fix it?

https://github.com/hintmedia/moderate_parameters/blob/2bb97aa11c48e6339ba6f4898cb7d60c70461178/lib/moderate_parameters/parameters.rb#L39

<img width="670" alt="Screenshot 2021-10-21 at 16 04 48" src="https://user-images.githubusercontent.com/14002692/138283349-feca790b-0a6b-4fa2-8627-e58fd34c5ef2.png">

**Comment by kyleboe** [comment]
Ok I think I understand the issue. `require` is intended to be used similarly to [`ActionController::Parameters` implementation of `require`](https://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-require) where there is a key with a hash value. Something like this:
```ruby
params = ActionController::Parameters.new({ user: { name: "test user", email: "test@user.com" } })

params.require(:user)
#=> <ActionController::Parameters {"name"=>"test user", "email"=>"test@user.com"} permitted: false>
```

The goal of `require` is not to reach terminal values (such as `"123"` in this case). Hopefully that clears things up and if you have any more questions feel free to comment below.
